apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appname }}{{ .Values.storage.pv }}
  labels:
    app: {{ .Values.appname }}
    tier: {{ .Values.tier }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{.Values.storage.className }}
  hostPath:
    path: {{ .Values.storage.path }}