apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appname }}
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}