---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: ClusterIP
  ports:
    - name: phpmyadmin
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: phpmyadmin