---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  ports:
    - name: phpmyadmin
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.phpmyadmin.nodePort }}
  selector:
    app: phpmyadmin