apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Values.appname }}-entrypoint
data:
  entrypoint.sh: |-
      #!/usr/bin/env bash
      set -Eeuo pipefail
      DBNAME="{{ .Values.database.name }}"
      HOST_DB="{{ .Values.database.host }}"
      USUARIO="{{ .Values.database.usuario }}"
      SENHA="{{ .Values.database.usuario_senha }}"

      DBEXISTS=$(mysql --batch --skip-column-names -h $HOST_DB -u root -psecret -e "SHOW DATABASES LIKE '"$DBNAME"';" | grep "$DBNAME" > /dev/null; echo "$?")
      if [ $DBEXISTS -eq 0 ];then
        echo ""
        sh /usr/local/bin/docker-entrypoint.sh
      else
        echo "Criando Database..."
        mysql -h $HOST_DB -u root -psecret -e "CREATE DATABASE "$DBNAME""
        mysql -h $HOST_DB -u root -psecret -e "CREATE USER '"$USUARIO"'@'%' IDENTIFIED BY '"$SENHA"';"
        mysql -h $HOST_DB -u root -psecret -e "GRANT ALL PRIVILEGES ON "$DBNAME".* TO '"$USUARIO"'@'%' WITH GRANT OPTION;"
        mysql -h $HOST_DB -u root -psecret -e "FLUSH PRIVILEGES;"
        mysql -h $HOST_DB -u root -psecret "$DBNAME" < /sql/init.sql
        sh /usr/local/bin/docker-entrypoint.sh
      fi