apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Values.appname }}-entrypoint
data:
  entrypoint.sh: |-
      #!/bin/bash
      set -e
      DBNAME="{{ .Values.database.name }}"
      DBEXISTS=$(mysql --batch --skip-column-names -h wordpress-db-mysql.database.svc.cluster.local -u root -psecret -e "SHOW DATABASES LIKE '"$DBNAME"';" | grep "$DBNAME" > /dev/null; echo "$?")
      if [ $DBEXISTS -eq 0 ];then
        sh /usr/local/bin/docker-entrypoint.sh
      else
        echo 'mysql -h wordpress-db-mysql.database.svc.cluster.local -u root -psecret -e "CREATE DATABASE {{ .Values.database.name }}"'
        echo 'mysql -h wordpress-db-mysql.database.svc.cluster.local -u root -psecret -e "CREATE USER '{{ .Values.database.usuario }}'@'%' IDENTIFIED BY '{{ .Values.database.usuario_senha }}';"'
        echo 'mysql -h wordpress-db-mysql.database.svc.cluster.local -u root -psecret -e "GRANT ALL PRIVILEGES ON {{ .Values.database.name }}.* TO '{{ .Values.database.usuario }}'@'%' WITH GRANT OPTION;"'
        echo 'mysql -h wordpress-db-mysql.database.svc.cluster.local -u root -psecret -e "CREATE DATABASE FLUSH PRIVILEGES;"'
        echo 'mysql -h wordpress-db-mysql.database.svc.cluster.local -u root -psecret {{ .Values.database.name }} < /sql/init.sql'
        sh /usr/local/bin/docker-entrypoint.sh
      fi