---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
type: Opaque
data:
  mysql-root-password: c2VjcmV0
  mysql-user: {{ .Values.database.user }}
  mysql-password: {{ .Values.database.user_password }}