---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    tier: {{ .Values.tier }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.appname }}
      port: 80
      protocol: TCP
  selector:
    app: {{ .Values.appname }}
    tier: {{ .Values.tier }}