apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    app: grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: grafana
  hostPath:
    path: /kubernetes/pv/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - multinode-demo-m02