apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-5.2.11
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
secrets:
  - name: grafana-admin