---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
spec:
  type: NodePort
  ports:
    - name: {{ .Values.appname }}
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.nodePort }}
  selector:
    app: {{ .Values.appname }}