---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
type: Opaque
data:
  mysql-root-password: "{{ .Values.database.root_password }}"