---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    tier: {{ .Values.tier }}
spec:
  type: NodePort
  ports:
    - name: mysql
      nodePort: {{ .Values.nodePort }}
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: {{ .Values.appname }}
    tier: {{ .Values.tier }}