appname: "wordpress-db-mysql"
tier: "mysql"
nodePort: 30010

storage:
   className: "wp-mysql-sc"
   size: 20Gi
   name: 'data-wp-mysql'
   path: '/kubernetes/pv/db/mysql/'

database:
  name: WPCLIENTE1
  root_password: c2VjcmV0